### ISSUE TITLE
Improve contributinh page

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_LabGuide#14]
- [x] check links
- [x] check if it is understandable
- [ ] improve language
- [x] add to always ask for a third person to review any change (eg Marco or Filippo)

**Comment by fcerpe** [comment]
-[] add link to markdown cheatsheet

**Comment by fcerpe** [comment]
- [ ] add disclaimer about sensitive data, they should be in separate files that are private and linked at in the guide
